### ISSUE TITLE
Proivde easy way to build examples

### ISSUE THREAD

**Issue by marcmo** [esrlabs/dlt-core#30]
using this structure:
```
my_library/
├── src/
│   ├── lib.rs  # Your library code
│   ├── some_module.rs
├── examples/
│   ├── example1.rs  # Example showcasing some feature
│   ├── example2.rs  # Another example
├── tests/  # Integration tests (optional)
│   ├── integration_test.rs
├── Cargo.toml
```
Cargo.toml might look s.th. like this:
``` toml
[package]
name = "my_library"
version = "0.1.0"
edition = "2021"

[dependencies]
# Add your dependencies here

[[example]]
name = "example1"
path = "examples/example1.rs"

[[example]]
name = "example2"
path = "examples/example2.rs"
```
then the examples can be built and run with cargo:
`cargo run --example example1`
